In [ ]:
!mkdir ~/.kaggle

In [ ]:
!mv kaggle.json ~/.kaggle/

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d kaggleprollc/phishing-url-websites-dataset-phiusiil

Dataset URL: https://www.kaggle.com/datasets/kaggleprollc/phishing-url-websites-dataset-phiusiil
License(s): CC-BY-SA-4.0
Downloading phishing-url-websites-dataset-phiusiil.zip to /content
 50% 8.00M/15.9M [00:00<00:00, 83.0MB/s]
100% 15.9M/15.9M [00:00<00:00, 97.9MB/s]

In [ ]:
!unzip phishing-url-websites-dataset-phiusiil.zip

Archive:  phishing-url-websites-dataset-phiusiil.zip
  inflating: PhiUSIIL_Phishing_URL_Dataset.csv

# Importing Dependencies

In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [3]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [4]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

# Dataset

In [5]:
df = pd.read_csv('/content/PhiUSIIL_Phishing_URL_Dataset.csv')

In [6]:
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [7]:
df = df[['URL', 'label']]

In [8]:
df.head()

                                  URL  label
0    https://www.southbankmosaics.com      1
1            https://www.uni-mainz.de      1
2      https://www.voicefmradio.co.uk      1
3         https://www.sfnmjournal.com      1
4  https://www.rewildingargentina.org      1

In [9]:
df.shape

(235795, 2)

In [10]:
df['label'].value_counts()

label
1    134850
0    100945
Name: count, dtype: int64

In [11]:
df.isnull().sum()

URL      0
label    0
dtype: int64

In [12]:
X = df['URL']
Y = df['label']

In [13]:
#converting textual data to numerical data
vectorizer = TfidfVectorizer(max_features = 600)
vectorizer.fit(X)

TfidfVectorizer(max_features=600)

In [14]:
X = vectorizer.transform(X)

In [15]:
print(X)

  (0, 170)	0.683834792181783
  (0, 287)	0.5072407522775285
  (0, 591)	0.5244776413066856
  (1, 187)	0.5012046021143349
  (1, 287)	0.12462789182879262
  (1, 542)	0.8465554760120566
  (1, 591)	0.12886295601033798
  (2, 169)	0.6134606136515519
  (2, 287)	0.20022241201946703
  (2, 541)	0.7353347336442313
  (2, 591)	0.20702630441500833
  (3, 170)	0.683834792181783
  (3, 287)	0.5072407522775285
  (3, 591)	0.5244776413066856
  (4, 287)	0.3239237447378284
  (4, 407)	0.8848132507040684
  (4, 591)	0.33493121528684316
  (5, 287)	0.3239237447378284
  (5, 407)	0.8848132507040684
  (5, 591)	0.33493121528684316
  (6, 170)	0.683834792181783
  (6, 287)	0.5072407522775285
  (6, 591)	0.5244776413066856
  (7, 170)	0.683834792181783
  (7, 287)	0.5072407522775285
  :	:
  (235787, 591)	0.242086857256935
  (235788, 170)	0.683834792181783
  (235788, 287)	0.5072407522775285
  (235788, 591)	0.5244776413066856
  (235789, 170)	0.15614101300172462
  (235789, 287)	0.11581903378106598
  (235789, 299)	0.5549635749547431
  (235789, 335)	0.7999250988851107
  (235789, 591)	0.11975475823495638
  (235790, 170)	0.683834792181783
  (235790, 287)	0.5072407522775285
  (235790, 591)	0.5244776413066856
  (235791, 269)	0.7363023842236112
  (235791, 287)	0.17155461704137967
  (235791, 541)	0.6300496900181974
  (235791, 591)	0.17738432982195668
  (235792, 120)	0.9664943944268163
  (235792, 287)	0.17844831540638922
  (235792, 591)	0.18451228758585053
  (235793, 194)	0.6457897351828484
  (235793, 287)	0.15277901036601774
  (235793, 587)	0.7480736540769545
  (235794, 170)	0.683834792181783
  (235794, 287)	0.5072407522775285
  (235794, 591)	0.5244776413066856

# Decision Tree

In [16]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, stratify=Y, random_state=1)

In [17]:
print(X.shape, x_train.shape, x_test.shape)

(235795, 600) (176846, 600) (58949, 600)

In [19]:
from sklearn.linear_model import LogisticRegression
# from sklearn.tree import DecisionTreeClassifier

In [20]:
model1 = LogisticRegression(max_iter=200, random_state=0)

In [21]:
model1.fit(x_train, y_train)

LogisticRegression(max_iter=200, random_state=0)

In [22]:
x_train_predict = model1.predict(x_train)
training_data_accuracy = accuracy_score(x_train_predict, y_train)
print(training_data_accuracy)

0.9941983420603236

In [23]:
x_test_predict = model1.predict(x_test)
test_data_accuracy = accuracy_score(x_test_predict, y_test)
print(test_data_accuracy)

0.9947412169841727

In [24]:
training_precision = precision_score(y_train, x_train_predict)
print('Training data precision score = ', training_precision)
training_recall = recall_score(y_train, x_train_predict)
print('Training data recall score = ', training_recall)
training_matrix = confusion_matrix(y_train, x_train_predict)
print('Training data confusion matrix = ', training_matrix)

Training data precision score =  0.9916222241865308
Training data recall score =  0.998289448965265
Training data confusion matrix =  [[ 74856    853]
 [   173 100964]]

In [25]:
testing_precision = precision_score(y_test, x_test_predict)
print('Testing data precision score = ', testing_precision)
testing_recall = recall_score(y_test, x_test_predict)
print('Testing data recall score = ', testing_recall)
testing_matrix = confusion_matrix(y_test, x_test_predict)
print('Testing data confusion matrix = ', testing_matrix)

Testing data precision score =  0.9924226788925907
Testing data recall score =  0.9984279061489633
Testing data confusion matrix =  [[24979   257]
 [   53 33660]]

In [26]:
def predict_text(input_text):
    # Transform the input text using the fitted vectorizer
    input_vector = vectorizer.transform([input_text])

    # Make the prediction
    prediction = model1.predict(input_vector)

    return prediction[0]

In [27]:
input_text = "www.google.com"
predicted_class = predict_text(input_text)
print(f"The predicted class for the input text is: {predicted_class}")

The predicted class for the input text is: 1

In [28]:
input_text = "https://www.uni-mainz.de"
predicted_class = predict_text(input_text)
print(f"The predicted class for the input text is: {predicted_class}")

The predicted class for the input text is: 1

In [29]:
input_text = "http://google.com-redirect@valimail.com"
predicted_class = predict_text(input_text)
print(f"The predicted class for the input text is: {predicted_class}")

The predicted class for the input text is: 0